nodes:
  - host_id: traffic-generator
    role: traffic-generator
    dependencies: [api-gateway]
  - host_id: api-gateway
    role: api-gateway
    dependencies: [processing-service]
  - host_id: processing-service
    role: processing-service
    dependencies: [data-service, worker-service]
  - host_id: data-service
    role: data-service
    dependencies: []
  - host_id: worker-service
    role: worker-service
    dependencies: []
