[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File /etc/fluent-bit/parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/machine/app.log
    Tag          app.${HOST_ID}
    Parser       app_json
    Refresh_Interval 5
    Rotate_Wait  30
    Mem_Buf_Limit 10MB
    Skip_Long_Lines On

[INPUT]
    Name         tail
    Path         /var/log/machine/system.log
    Tag          system.${HOST_ID}
    Parser       app_json
    Refresh_Interval 5
    Rotate_Wait  30
    Mem_Buf_Limit 10MB
    Skip_Long_Lines On

[FILTER]
    Name         modify
    Match        *
    Add          project AgenticProactiveMonitor
    Add          environment thesis-lab
    Add          host_id ${HOST_ID}
    Add          machine_role ${MACHINE_ROLE}
    Add          monitored_by fluent-bit

[OUTPUT]
    Name                 opensearch
    Match                *
    Host                 opensearch
    Port                 9200
    TLS                  Off
    Logstash_Format      On
    Logstash_Prefix      logs
    Suppress_Type_Name   On
    Generate_ID          On
    Retry_Limit          False
