[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "$HOST_ID"
  omit_hostname = false
  skip_processors_after_aggregators = false

[global_tags]
  project = "AgenticProactiveMonitor"
  environment = "thesis-lab"
  monitored_by = "telegraf"
  host_id = "$HOST_ID"
  machine_role = "$MACHINE_ROLE"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.disk]]

[[inputs.diskio]]

[[inputs.net]]

[[inputs.system]]

[[inputs.swap]]

[[inputs.processes]]

[[inputs.kernel]]

[[outputs.opensearch]]
  urls = ["http://opensearch:9200"]
  index_name = "metrics-{{.Time.Format \"2006.01.02\"}}"
  timeout = "10s"
  enable_sniffer = false
  health_check_interval = "10s"
  manage_template = false
  template_name = "telegraf"
