from __future__ import annotations

import os
import random
import re
import time
from dataclasses import dataclass

import requests

from common.logging_utils import new_request_id, write_log

SERVICE_NAME = "traffic-generator"
TARGET_URL = os.getenv("TARGET_URL", "http://api-gateway:5000").rstrip("/")
REQUEST_TIMEOUT_SECONDS = float(os.getenv("REQUEST_TIMEOUT_SECONDS", "5"))
MIN_INTERVAL_SECONDS = float(os.getenv("TRAFFIC_MIN_INTERVAL_SECONDS", "2"))
MAX_INTERVAL_SECONDS = float(os.getenv("TRAFFIC_MAX_INTERVAL_SECONDS", "5"))

NOTE_ID_PATTERN = re.compile(r'/notes/(\d+)')


@dataclass
class TrafficState:
    note_ids: set[int]
    sequence: int = 0


session = requests.Session()
state = TrafficState(note_ids=set())


def request_headers(request_id: str) -> dict[str, str]:
    return {"X-Request-ID": request_id, "User-Agent": "notes-platform-traffic-generator/1.0"}


def record_request(
    *,
    action: str,
    request_id: str,
    method: str,
    path: str,
    status_code: int | None,
    latency_ms: float,
    level: str = "INFO",
    error_type: str | None = None,
) -> None:
    fields: dict[str, object] = {
        "action": action,
        "method": method,
        "path": path,
        "latency_ms": latency_ms,
    }
    if status_code is not None:
        fields["status_code"] = status_code
    if error_type is not None:
        fields["error_type"] = error_type

    write_log(
        service=SERVICE_NAME,
        level=level,
        event_type="synthetic_user_action_completed" if level == "INFO" else "synthetic_user_action_failed",
        message=f"Synthetic user action {action} completed" if level == "INFO" else f"Synthetic user action {action} failed",
        request_id=request_id,
        **fields,
    )


def perform_request(
    action: str,
    method: str,
    path: str,
    *,
    data: dict[str, str] | None = None,
    allow_redirects: bool = True,
) -> requests.Response | None:
    request_id = new_request_id()
    start = time.perf_counter()

    try:
        response = session.request(
            method,
            f"{TARGET_URL}{path}",
            headers=request_headers(request_id),
            data=data,
            timeout=REQUEST_TIMEOUT_SECONDS,
            allow_redirects=allow_redirects,
        )
    except requests.RequestException as exc:
        latency_ms = round((time.perf_counter() - start) * 1000, 3)
        record_request(
            action=action,
            request_id=request_id,
            method=method,
            path=path,
            status_code=None,
            latency_ms=latency_ms,
            level="ERROR",
            error_type=type(exc).__name__,
        )
        return None

    latency_ms = round((time.perf_counter() - start) * 1000, 3)
    level = "INFO" if response.status_code < 500 else "ERROR"
    record_request(
        action=action,
        request_id=request_id,
        method=method,
        path=path,
        status_code=response.status_code,
        latency_ms=latency_ms,
        level=level,
    )
    return response


def refresh_note_ids() -> None:
    response = perform_request("browse_dashboard", "GET", "/")
    if response is None or response.status_code >= 400:
        return

    state.note_ids.update(int(note_id) for note_id in NOTE_ID_PATTERN.findall(response.text))


def create_note() -> None:
    state.sequence += 1
    title = f"Synthetic note {state.sequence}"
    content = (
        "Automatically generated by the monitored-system traffic generator "
        f"at sequence {state.sequence}."
    )
    response = perform_request(
        "create_note",
        "POST",
        "/notes/new",
        data={"title": title, "content": content},
        allow_redirects=False,
    )
    if response is None or response.status_code not in {301, 302, 303, 307, 308}:
        return

    location = response.headers.get("Location", "")
    match = NOTE_ID_PATTERN.search(location)
    if match:
        state.note_ids.add(int(match.group(1)))


def read_note() -> None:
    if not state.note_ids:
        refresh_note_ids()
    if not state.note_ids:
        create_note()
        return

    note_id = random.choice(tuple(state.note_ids))
    response = perform_request("read_note", "GET", f"/notes/{note_id}")
    if response is not None and response.status_code == 404:
        state.note_ids.discard(note_id)


def update_note() -> None:
    if not state.note_ids:
        refresh_note_ids()
    if not state.note_ids:
        create_note()
        return

    note_id = random.choice(tuple(state.note_ids))
    state.sequence += 1
    response = perform_request(
        "update_note",
        "POST",
        f"/notes/{note_id}/edit",
        data={
            "title": f"Updated synthetic note {note_id}",
            "content": f"Synthetic update number {state.sequence} for note {note_id}.",
        },
        allow_redirects=False,
    )
    if response is not None and response.status_code == 404:
        state.note_ids.discard(note_id)


def delete_note() -> None:
    if len(state.note_ids) < 3:
        create_note()
        return

    note_id = random.choice(tuple(state.note_ids))
    response = perform_request(
        "delete_note",
        "POST",
        f"/notes/{note_id}/delete",
        allow_redirects=False,
    )
    if response is not None and response.status_code in {301, 302, 303, 307, 308}:
        state.note_ids.discard(note_id)


def choose_action() -> None:
    action = random.choices(
        population=[refresh_note_ids, create_note, read_note, update_note, delete_note],
        weights=[40, 20, 25, 10, 5],
        k=1,
    )[0]
    action()


def main() -> None:
    write_log(
        service=SERVICE_NAME,
        level="INFO",
        event_type="service_started",
        message="Synthetic user traffic generator started",
        target_url=TARGET_URL,
        min_interval_seconds=MIN_INTERVAL_SECONDS,
        max_interval_seconds=MAX_INTERVAL_SECONDS,
    )

    while True:
        choose_action()
        time.sleep(random.uniform(MIN_INTERVAL_SECONDS, MAX_INTERVAL_SECONDS))


if __name__ == "__main__":
    main()
